-- CreateTable
CREATE TABLE "customers" (
    "MSISDN" TEXT NOT NULL,
    "CPF" TEXT NOT NULL,
    "CUSNAME" TEXT NOT NULL,
    "CUSCOMPANY" TEXT NOT NULL,
    "OPERATOR" TEXT NOT NULL,
    "OPERATOR_ID" TEXT NOT NULL,

    CONSTRAINT "customers_pkey" PRIMARY KEY ("MSISDN")
);
